version: '3'

services:
  app:
    build:
      context: ./app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:8080"
    depends_on:
      - app

  db:
    build:
      context: ./db
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
